//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public System.Guid MaterialID { get; set; }
        public string Tkin { get; set; }
        public Nullable<System.DateTime> DateEfir { get; set; }
        public string Title { get; set; }
        public System.Guid JanrID { get; set; }
        public Nullable<double> Raiting { get; set; }
    
        public virtual Janr Janr { get; set; }
        public virtual MaterialDict MaterialDict { get; set; }
    }
}
